### ISSUE TITLE
Implement Batch Read Functionality

### ISSUE THREAD

**Issue by tws4793** [smucclaw/l4meta#3]
I would like to request anyone to help implement the **Batch Read** functionality of `l4meta`.

## Purpose

The current implementation only allows reading/writing a single document. This is one of the planned features of `l4meta` to allow users to read/write metadata from multiple documents.

## How it should Work

Assuming a `contracts` directory with 3 PDFs within the directory as follows:

```
contracts
├── alice.pdf
├── bob.pdf
└── mallory.pdf
```

When the following command is run within the `contracts` directory:

```console
$ l4meta *.pdf
```

It should result in 3 `json` files with names similar to the original PDFs being produced, such that the resultant directory now becomes:

```
contracts
├── alice.pdf
├── alice.json
├── bob.pdf
├── bob.json
├── mallory.pdf
└── mallory.json
```

However, if within the same contracts directory, there are two similarly named files that are of a `pdf` and `json`, like so:

```
contracts
├── alice.pdf
├── alice.json
└── mallory.pdf
```

`l4meta` must return an error. I'd like to get feedback as to how the error should be like.

The command and the program should have support for output to `yml` or `yaml` files (with the `-y` or `--yaml` option).

## Existing Work

I have earlier written some code for this functionality, the code snippet from `meta.py` is appended below:

```python
def read_multiple_files(
        self,
        filenames: List[str],
        output_format: str = 'json') -> str:
    """Read metadata from multiple files."""
    self.exit_on_error(
            not filenames,
            'No files to read!')
    if len(filenames) == 1:
        return self.read_file(filenames[0], output_format)
    print('Using batch mode')
    if not self.check_duplicate_metadata_file(filenames, output_format):
        for file in filenames:
            metadata = self.read_file(file, output_format)
            name, ext = os.path.splitext(file)
            with open(name + '.json', 'w') as out:
                out.write(metadata)

def check_duplicate_metadata_file(
        self,
        filenames: List[str],
        output_format: str = 'json') -> bool:
    """Check if there are any duplicate files"""
    metafiles = filter(
            lambda file: file.endswith(output_format),
            os.listdir(os.curdir))
    duplicate_names = set(filenames).intersection(metafiles)
    self.exit_on_error(
            len(duplicate_names) > 0,
            'Duplicate metadata file detected. '
            'Please remove the duplicates to continue.')
    return False

def list_files(
        self,
        filetypes: List[str],
        directory: str = os.curdir) -> List[str]:
    files = os.listdir(directory)
    pass
```

## TODO

Modify the `meta.py` and `cli.py` files to include batch read functionality. In short,

- [x] Check for duplicate named files
- [x] Write out metadata to a file (must support writing out to both `json` and `yml` files)
- [x] Suggest what an appropriate error message (in case it happens) should be

**Comment by tws4793** [comment]
Update: Implemented batch read, check the `refactor` branch. Left with the check for duplicate named files.

**Comment by tws4793** [comment]
Check for duplicate named files completed, check the `refactor` branch.

Meanwhile I just put an arbitrary `error: duplicate filenames present` error message. Should be good enough for now.
